#!/usr/bin/env ruby
# Injects Capacitor push-notifications callback handlers into AppDelegate.swift.
#
# The default AppDelegate.swift generated by `cap add ios` doesn't include
# the UIApplicationDelegate methods that forward APNs token callbacks to
# Capacitor via NotificationCenter. Without these, the
# @capacitor/push-notifications plugin's `register()` call silently
# completes but the device token never reaches the JavaScript bridge —
# because iOS calls AppDelegate methods, not the plugin directly.
#
# This script is idempotent — running twice is a no-op.
#
# Usage:
#   ruby scripts/inject_push_appdelegate.rb [path/to/AppDelegate.swift]
#   (defaults to ios/App/App/AppDelegate.swift)

appdelegate_path = ARGV[0] || 'ios/App/App/AppDelegate.swift'

unless File.exist?(appdelegate_path)
  puts "ERROR: #{appdelegate_path} not found!"
  exit 1
end

content = File.read(appdelegate_path)

if content.include?('didRegisterForRemoteNotificationsWithDeviceToken')
  puts "Push handlers already present in #{appdelegate_path}, skipping."
  exit 0
end

push_handlers = <<~SWIFT

    // ─── Push Notifications (injected by inject_push_appdelegate.rb) ─────────
    // Forward APNs token callbacks to Capacitor's NotificationCenter so the
    // @capacitor/push-notifications plugin can deliver tokens to JavaScript.

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }
SWIFT

# Insert before the final closing `}` of the AppDelegate class.
# The default file ends with `}\n` (class closing brace, newline, EOF).
patched = content.sub(/\n\}\s*\z/m, "\n#{push_handlers}}\n")

if patched == content
  puts 'ERROR: Could not find class closing `}` to patch!'
  puts 'AppDelegate.swift content:'
  puts content
  exit 1
end

File.write(appdelegate_path, patched)
puts "Successfully injected push notification handlers into #{appdelegate_path}."
