import { useMemo } from "react";
import type { ReactNode } from "react";

/**
 * AuthDoodleBackground
 * --------------------
 * WhatsApp-wallpaper-style doodle pattern for auth pages. Scatter mode:
 * positions are generated by seeded random rejection-sampling so the layout
 * looks genuinely random (not gridded) but no two icons overlap.
 *
 * Tuning knobs (top of component):
 *   TILE      — pattern tile size (smaller = more repetition across screen)
 *   TARGET    — how many icons per tile (more = denser)
 *   MIN_DIST  — minimum center-to-center distance (smaller = tighter packing)
 *   PAD       — keep icons this many px away from tile edges
 *   SEED      — change to re-roll the random layout
 *
 * Color palette: 4 saturated brand-aligned hues, each placement gets one
 * at random — gives the wallpaper its mixed-neon feel.
 */

// ===== Icon library — each entry is an SVG fragment, drawn centered on origin =====
const ICONS = {
  plus: (
    <>
      <line x1="-9" y1="0" x2="9" y2="0" />
      <line x1="0" y1="-9" x2="0" y2="9" />
    </>
  ),
  equals: (
    <>
      <line x1="-9" y1="-3" x2="9" y2="-3" />
      <line x1="-9" y1="3" x2="9" y2="3" />
    </>
  ),
  multiply: (
    <>
      <line x1="-6" y1="-6" x2="6" y2="6" />
      <line x1="-6" y1="6" x2="6" y2="-6" />
    </>
  ),
  minus: <line x1="-9" y1="0" x2="9" y2="0" />,
  divide: (
    <>
      <line x1="-9" y1="0" x2="9" y2="0" />
      <circle cx="0" cy="-4" r="1.2" />
      <circle cx="0" cy="4" r="1.2" />
    </>
  ),
  coin: (
    <>
      <circle cx="0" cy="0" r="10" />
      <line x1="0" y1="-6" x2="0" y2="6" />
      <path d="M 4 -3 Q 4 -5 0 -5 Q -4 -5 -4 -2 Q -4 1 0 1 Q 4 1 4 4 Q 4 5 0 5 Q -4 5 -4 3" />
    </>
  ),
  wallet: (
    <>
      <rect x="-10" y="-7" width="20" height="14" rx="2" />
      <path d="M -10 -2 H 10" />
      <circle cx="6" cy="2" r="1.5" />
    </>
  ),
  dollar: (
    <>
      <line x1="0" y1="-12" x2="0" y2="12" />
      <path d="M 6 -7 Q 6 -9 0 -9 Q -6 -9 -6 -5 Q -6 -1 0 1 Q 6 3 6 7 Q 6 9 0 9 Q -6 9 -6 7" />
    </>
  ),
  calculator: (
    <>
      <rect x="-8" y="-11" width="16" height="22" rx="2" />
      <rect x="-6" y="-9" width="12" height="4" />
      <line x1="-6" y1="-1" x2="6" y2="-1" />
      <line x1="-6" y1="3" x2="6" y2="3" />
      <line x1="-6" y1="7" x2="6" y2="7" />
      <line x1="-2" y1="-3" x2="-2" y2="9" />
      <line x1="2" y1="-3" x2="2" y2="9" />
    </>
  ),
  receipt: (
    <>
      <path d="M -8 -12 H 8 V 10 L 5 12 L 2 10 L -2 12 L -5 10 L -8 12 Z" />
      <line x1="-5" y1="-7" x2="5" y2="-7" />
      <line x1="-5" y1="-3" x2="5" y2="-3" />
      <line x1="-5" y1="1" x2="3" y2="1" />
    </>
  ),
  coffee: (
    <>
      <path d="M -8 -4 H 7 V 6 Q 7 10 3 10 H -4 Q -8 10 -8 6 Z" />
      <path d="M 7 -1 Q 12 -1 12 3 Q 12 7 7 7" />
      <path d="M -4 -10 Q -2 -8 -4 -6" />
      <path d="M 2 -10 Q 4 -8 2 -6" />
    </>
  ),
  forkknife: (
    <>
      <line x1="-3" y1="-10" x2="-3" y2="10" />
      <line x1="-5" y1="-10" x2="-5" y2="-5" />
      <line x1="-1" y1="-10" x2="-1" y2="-5" />
      <line x1="5" y1="-10" x2="5" y2="10" />
      <path d="M 5 -10 Q 9 -8 9 -3 Q 9 0 5 0" />
    </>
  ),
  popcorn: (
    <>
      <path d="M -6 -3 L -7 11 H 7 L 6 -3 Z" />
      <line x1="-6" y1="0" x2="6" y2="0" />
      <circle cx="-3" cy="-6" r="2" />
      <circle cx="2" cy="-7" r="2" />
      <circle cx="6" cy="-4" r="1.5" />
    </>
  ),
  heart: (
    <path d="M 0 8 C -8 2 -10 -3 -7 -7 C -4 -10 -1 -8 0 -5 C 1 -8 4 -10 7 -7 C 10 -3 8 2 0 8 Z" />
  ),
  twopeople: (
    <>
      <circle cx="-7" cy="-4" r="3" />
      <path d="M -13 8 Q -7 1 -1 8" />
      <circle cx="7" cy="-4" r="3" />
      <path d="M 1 8 Q 7 1 13 8" />
    </>
  ),
  gift: (
    <>
      <rect x="-9" y="-3" width="18" height="12" rx="0.5" />
      <line x1="-9" y1="3" x2="9" y2="3" />
      <line x1="0" y1="-3" x2="0" y2="9" />
      <path d="M -3 -3 Q -7 -8 -3 -10 Q 0 -8 0 -3" />
      <path d="M 3 -3 Q 7 -8 3 -10 Q 0 -8 0 -3" />
    </>
  ),
} satisfies Record<string, ReactNode>;

type IconKey = keyof typeof ICONS;
const ICON_KEYS = Object.keys(ICONS) as IconKey[];

// ===== Color palette — saturated, brand-aligned =====
const COLORS = [
  "#14B8A6", // teal — Spliiit accent
  "#EC4899", // pink — food / hearts
  "#F59E0B", // amber — money / receipts
  "#3B82F6", // blue — group / people
];

// ===== Seeded RNG (mulberry32) — same layout every render =====
function makeRng(seed: number) {
  let a = seed;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function AuthDoodleBackground() {
  // ===== Tuning knobs =====
  const TILE = 280; // tile size in px
  const TARGET = 75; // icons per tile (more = denser)
  const MIN_DIST = 28; // min center-to-center distance (smaller = tighter packing)
  const PAD = 16; // keep icons this many px away from tile edges
  const SEED = 42; // change to re-roll the random layout

  const placements = useMemo(() => {
    const rng = makeRng(SEED);
    const result: Array<{ x: number; y: number; key: IconKey; color: string }> = [];
    let attempts = 0;
    while (result.length < TARGET && attempts < 10000) {
      attempts++;
      const x = PAD + rng() * (TILE - 2 * PAD);
      const y = PAD + rng() * (TILE - 2 * PAD);
      const tooClose = result.some((p) => Math.hypot(p.x - x, p.y - y) < MIN_DIST);
      if (tooClose) continue;
      const key = ICON_KEYS[Math.floor(rng() * ICON_KEYS.length)];
      const color = COLORS[Math.floor(rng() * COLORS.length)];
      result.push({ x, y, key, color });
    }
    return result;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <svg
      className="absolute inset-0 w-full h-full pointer-events-none opacity-[0.45] dark:opacity-[0.75]"
      aria-hidden="true"
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        <pattern
          id="spliiit-auth-doodle"
          x="0"
          y="0"
          width={TILE}
          height={TILE}
          patternUnits="userSpaceOnUse"
        >
          <g
            fill="none"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            {placements.map((p, i) => (
              <g
                key={i}
                transform={`translate(${p.x.toFixed(1)} ${p.y.toFixed(1)})`}
                stroke={p.color}
              >
                {ICONS[p.key]}
              </g>
            ))}
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#spliiit-auth-doodle)" />
    </svg>
  );
}
